# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)



runners = Runner.create([
	{first_name: "Becki", 	last_name: "Spellman", 		age: 32, profession: "blahblah", 	website: "www.beckispellman.com", 	has_coach: true, 	coach_name: "Glenn Andrews", 	twitter_handle: "@beckimichael9", 	has_spouse: false, 	has_children: false, 	num_of_children: 0, is_qualified: false, 	q_standard: "", 	marathon_pr: "2:44:44", first_marathon_time:"0:00:00", 	avg_job_hrs: 40, 	bio: "'Rocket' on Salty Running", 								peak_mileage_wkly: 80, img_url:"http://2.bp.blogspot.com/-LVKNArEOe6A/UjmibW0phLI/AAAAAAAAAJQ/0ZG6IDPc6Zk/s1600/IMG_0225.JPG"},
	{first_name: "Jessica", last_name: "Kuhr Odorcic", 	age: 34, profession: "A hard job", 	website: "www.jessicakuhro.com", 	has_coach: true, 	coach_name: "Glenn Andrews", 	twitter_handle: "@jessicaodorcic", 	has_spouse: true,	has_children: false, 	num_of_children: 0, is_qualified: true, 	q_standard: "B", 	marathon_pr: "2:51:50", first_marathon_time:"", 		avg_job_hrs: 40,	bio: "Check out an interview with Jessica on Salty Running", 	peak_mileage_wkly: 65, img_url:"http://www.saltyrunning.com/wp-content/uploads/2015/11/odorcic.jpg"},
	{first_name: "Laura", last_name: "Pizmoht", 		age: 41, profession: "Stay at home Mom", website: "www.saltyrunning.com", 	has_coach: false, 	coach_name: "", 			twitter_handle: "@saltyone", 		has_spouse: true,	has_children: true, 	num_of_children: 3, is_qualified: true, 	q_standard: "A", 	marathon_pr: "2:25:00", first_marathon_time:"4:10:00", 	avg_job_hrs: 168,	bio: "Laura is the Salty of Salty Running and is so cool.", 	peak_mileage_wkly: 800, img_url:"http://i0.wp.com/www.saltyrunning.com/wp-content/uploads/2014/12/1005981_10151526195048093_1376354763_n-e1419970785126.jpg"},
	{first_name: "Becki", 	last_name: "Spellman", 		age: 32, profession: "blahblah", 	website: "www.beckispellman.com", 	has_coach: true, 	coach_name: "Glenn Andrews", 	twitter_handle: "@beckimichael9", 	has_spouse: false, 	has_children: false, 	num_of_children: 0, is_qualified: false, 	q_standard: "", 	marathon_pr: "2:44:44", first_marathon_time:"0:00:00", 	avg_job_hrs: 40, 	bio: "'Rocket' on Salty Running", 								peak_mileage_wkly: 80, img_url:"http://2.bp.blogspot.com/-LVKNArEOe6A/UjmibW0phLI/AAAAAAAAAJQ/0ZG6IDPc6Zk/s1600/IMG_0225.JPG"},
	{first_name: "Jessica", last_name: "Kuhr Odorcic", 	age: 34, profession: "A hard job", 	website: "www.jessicakuhro.com", 	has_coach: true, 	coach_name: "Glenn Andrews", 	twitter_handle: "@jessicaodorcic", 	has_spouse: true,	has_children: false, 	num_of_children: 0, is_qualified: true, 	q_standard: "B", 	marathon_pr: "2:51:50", first_marathon_time:"", 		avg_job_hrs: 40,	bio: "Check out an interview with Jessica on Salty Running", 	peak_mileage_wkly: 65, img_url:"http://www.saltyrunning.com/wp-content/uploads/2015/11/odorcic.jpg"},
	{first_name: "Laura", last_name: "Pizmoht", 		age: 41, profession: "Stay at home Mom", website: "www.saltyrunning.com", 	has_coach: false, 	coach_name: "", 			twitter_handle: "@saltyone", 		has_spouse: true,	has_children: true, 	num_of_children: 3, is_qualified: true, 	q_standard: "A", 	marathon_pr: "2:25:00", first_marathon_time:"4:10:00", 	avg_job_hrs: 168,	bio: "Laura is the Salty of Salty Running and is so cool.", 	peak_mileage_wkly: 800, img_url:"http://i0.wp.com/www.saltyrunning.com/wp-content/uploads/2014/12/1005981_10151526195048093_1376354763_n-e1419970785126.jpg"},
	{first_name: "Becki", 	last_name: "Spellman", 		age: 32, profession: "blahblah", 	website: "www.beckispellman.com", 	has_coach: true, 	coach_name: "Glenn Andrews", 	twitter_handle: "@beckimichael9", 	has_spouse: false, 	has_children: false, 	num_of_children: 0, is_qualified: false, 	q_standard: "", 	marathon_pr: "2:44:44", first_marathon_time:"0:00:00", 	avg_job_hrs: 40, 	bio: "'Rocket' on Salty Running", 								peak_mileage_wkly: 80, img_url:"http://2.bp.blogspot.com/-LVKNArEOe6A/UjmibW0phLI/AAAAAAAAAJQ/0ZG6IDPc6Zk/s1600/IMG_0225.JPG"},
	{first_name: "Jessica", last_name: "Kuhr Odorcic", 	age: 34, profession: "A hard job", 	website: "www.jessicakuhro.com", 	has_coach: true, 	coach_name: "Glenn Andrews", 	twitter_handle: "@jessicaodorcic", 	has_spouse: true,	has_children: false, 	num_of_children: 0, is_qualified: true, 	q_standard: "B", 	marathon_pr: "2:51:50", first_marathon_time:"", 		avg_job_hrs: 40,	bio: "Check out an interview with Jessica on Salty Running", 	peak_mileage_wkly: 65, img_url:"http://www.saltyrunning.com/wp-content/uploads/2015/11/odorcic.jpg"},
	{first_name: "Laura", last_name: "Pizmoht", 		age: 41, profession: "Stay at home Mom", website: "www.saltyrunning.com", 	has_coach: false, 	coach_name: "", 			twitter_handle: "@saltyone", 		has_spouse: true,	has_children: true, 	num_of_children: 3, is_qualified: true, 	q_standard: "A", 	marathon_pr: "2:25:00", first_marathon_time:"4:10:00", 	avg_job_hrs: 168,	bio: "Laura is the Salty of Salty Running and is so cool.", 	peak_mileage_wkly: 800, img_url:"http://i0.wp.com/www.saltyrunning.com/wp-content/uploads/2014/12/1005981_10151526195048093_1376354763_n-e1419970785126.jpg"},
	{first_name: "Becki", 	last_name: "Spellman", 		age: 32, profession: "blahblah", 	website: "www.beckispellman.com", 	has_coach: true, 	coach_name: "Glenn Andrews", 	twitter_handle: "@beckimichael9", 	has_spouse: false, 	has_children: false, 	num_of_children: 0, is_qualified: false, 	q_standard: "", 	marathon_pr: "2:44:44", first_marathon_time:"0:00:00", 	avg_job_hrs: 40, 	bio: "'Rocket' on Salty Running", 								peak_mileage_wkly: 80, img_url:"http://2.bp.blogspot.com/-LVKNArEOe6A/UjmibW0phLI/AAAAAAAAAJQ/0ZG6IDPc6Zk/s1600/IMG_0225.JPG"},
	{first_name: "Jessica", last_name: "Kuhr Odorcic", 	age: 34, profession: "A hard job", 	website: "www.jessicakuhro.com", 	has_coach: true, 	coach_name: "Glenn Andrews", 	twitter_handle: "@jessicaodorcic", 	has_spouse: true,	has_children: false, 	num_of_children: 0, is_qualified: true, 	q_standard: "B", 	marathon_pr: "2:51:50", first_marathon_time:"", 		avg_job_hrs: 40,	bio: "Check out an interview with Jessica on Salty Running", 	peak_mileage_wkly: 65, img_url:"http://www.saltyrunning.com/wp-content/uploads/2015/11/odorcic.jpg"},
	{first_name: "Laura", last_name: "Pizmoht", 		age: 41, profession: "Stay at home Mom", website: "www.saltyrunning.com", 	has_coach: false, 	coach_name: "", 			twitter_handle: "@saltyone", 		has_spouse: true,	has_children: true, 	num_of_children: 3, is_qualified: true, 	q_standard: "A", 	marathon_pr: "2:25:00", first_marathon_time:"4:10:00", 	avg_job_hrs: 168,	bio: "Laura is the Salty of Salty Running and is so cool.", 	peak_mileage_wkly: 800, img_url:"http://i0.wp.com/www.saltyrunning.com/wp-content/uploads/2014/12/1005981_10151526195048093_1376354763_n-e1419970785126.jpg"},
	{first_name: "Becki", 	last_name: "Spellman", 		age: 32, profession: "blahblah", 	website: "www.beckispellman.com", 	has_coach: true, 	coach_name: "Glenn Andrews", 	twitter_handle: "@beckimichael9", 	has_spouse: false, 	has_children: false, 	num_of_children: 0, is_qualified: false, 	q_standard: "", 	marathon_pr: "2:44:44", first_marathon_time:"0:00:00", 	avg_job_hrs: 40, 	bio: "'Rocket' on Salty Running", 								peak_mileage_wkly: 80, img_url:"http://2.bp.blogspot.com/-LVKNArEOe6A/UjmibW0phLI/AAAAAAAAAJQ/0ZG6IDPc6Zk/s1600/IMG_0225.JPG"},
	{first_name: "Jessica", last_name: "Kuhr Odorcic", 	age: 34, profession: "A hard job", 	website: "www.jessicakuhro.com", 	has_coach: true, 	coach_name: "Glenn Andrews", 	twitter_handle: "@jessicaodorcic", 	has_spouse: true,	has_children: false, 	num_of_children: 0, is_qualified: true, 	q_standard: "B", 	marathon_pr: "2:51:50", first_marathon_time:"", 		avg_job_hrs: 40,	bio: "Check out an interview with Jessica on Salty Running", 	peak_mileage_wkly: 65, img_url:"http://www.saltyrunning.com/wp-content/uploads/2015/11/odorcic.jpg"},
	{first_name: "Laura", last_name: "Pizmoht", 		age: 41, profession: "Stay at home Mom", website: "www.saltyrunning.com", 	has_coach: false, 	coach_name: "", 			twitter_handle: "@saltyone", 		has_spouse: true,	has_children: true, 	num_of_children: 3, is_qualified: true, 	q_standard: "A", 	marathon_pr: "2:25:00", first_marathon_time:"4:10:00", 	avg_job_hrs: 168,	bio: "Laura is the Salty of Salty Running and is so cool.", 	peak_mileage_wkly: 800, img_url:"http://i0.wp.com/www.saltyrunning.com/wp-content/uploads/2014/12/1005981_10151526195048093_1376354763_n-e1419970785126.jpg"},
	]) 







